IgnorePath '/boot/*'

IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/.updated'
IgnorePath '/etc/ca-certificates/*'
IgnorePath '/etc/ssl/*'
IgnorePath '/etc/systemd/*'
IgnorePath '/etc/fonts/*'
IgnorePath '/etc/fstab'
IgnorePath '/etc/group'
IgnorePath '/etc/group-'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/pacman.d/*'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/mkinitcpio.d/*'
IgnorePath '/etc/resolv.conf'
IgnorePath '/etc/passwd'
IgnorePath '/etc/shells'
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/subgid'
IgnorePath '/etc/subuid'

IgnorePath '/lost+found'

IgnorePath '/usr/*'
IgnorePath '/var/*'
