icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "net"
interval = 1

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 5
minimum = 5
maximum = 100

[[block]]
block = "cpu"
interval=1
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

# [[block]]
# block = "bluetooth"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
interval = 5
warning = 40
critical = 30
full_threshold = 80
empty_threshold = 20
